/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupabaseRouteImport } from './routes/supabase'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ComponentsDemoRouteImport } from './routes/components-demo'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QiemanLongWinPlanRouteImport } from './routes/qieman/long-win-plan'
import { Route as ApiTgSearchRouteImport } from './routes/api/tg-search'
import { Route as ApiSkillsRouteImport } from './routes/api/skills'
import { Route as ApiNotifyRouteImport } from './routes/api/notify'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiExchangeRateRouteImport } from './routes/api/exchange-rate'
import { Route as ApiChatUploadPolicyRouteImport } from './routes/api/chat-upload-policy'
import { Route as ApiChatOcrRouteImport } from './routes/api/chat-ocr'
import { Route as ApiChatObjectUrlRouteImport } from './routes/api/chat-object-url'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAiModelsRouteImport } from './routes/api/ai-models'
import { Route as ApiSkillsSkillIdRouteImport } from './routes/api/skills.$skillId'
import { Route as ApiQiemanLongWinPlanNotifyRouteImport } from './routes/api/qieman/long-win-plan-notify'
import { Route as ApiQiemanLongWinPlanRouteImport } from './routes/api/qieman/long-win-plan'
import { Route as ApiQiemanLongWinHoldingsDiffNotifyRouteImport } from './routes/api/qieman/long-win-holdings-diff-notify'
import { Route as ApiQiemanLongWinHoldingsDiffRouteImport } from './routes/api/qieman/long-win-holdings-diff'
import { Route as ApiFilesWriteRouteImport } from './routes/api/files/write'
import { Route as ApiFilesStatRouteImport } from './routes/api/files/stat'
import { Route as ApiFilesReadRouteImport } from './routes/api/files/read'
import { Route as ApiFilesMoveRouteImport } from './routes/api/files/move'
import { Route as ApiFilesMkdirRouteImport } from './routes/api/files/mkdir'
import { Route as ApiFilesListRouteImport } from './routes/api/files/list'
import { Route as ApiFilesDeleteRouteImport } from './routes/api/files/delete'

const SupabaseRoute = SupabaseRouteImport.update({
  id: '/supabase',
  path: '/supabase',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDemoRoute = ComponentsDemoRouteImport.update({
  id: '/components-demo',
  path: '/components-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QiemanLongWinPlanRoute = QiemanLongWinPlanRouteImport.update({
  id: '/qieman/long-win-plan',
  path: '/qieman/long-win-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTgSearchRoute = ApiTgSearchRouteImport.update({
  id: '/api/tg-search',
  path: '/api/tg-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsRoute = ApiSkillsRouteImport.update({
  id: '/api/skills',
  path: '/api/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyRoute = ApiNotifyRouteImport.update({
  id: '/api/notify',
  path: '/api/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExchangeRateRoute = ApiExchangeRateRouteImport.update({
  id: '/api/exchange-rate',
  path: '/api/exchange-rate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatUploadPolicyRoute = ApiChatUploadPolicyRouteImport.update({
  id: '/api/chat-upload-policy',
  path: '/api/chat-upload-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatOcrRoute = ApiChatOcrRouteImport.update({
  id: '/api/chat-ocr',
  path: '/api/chat-ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatObjectUrlRoute = ApiChatObjectUrlRouteImport.update({
  id: '/api/chat-object-url',
  path: '/api/chat-object-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiModelsRoute = ApiAiModelsRouteImport.update({
  id: '/api/ai-models',
  path: '/api/ai-models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsSkillIdRoute = ApiSkillsSkillIdRouteImport.update({
  id: '/$skillId',
  path: '/$skillId',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiQiemanLongWinPlanNotifyRoute =
  ApiQiemanLongWinPlanNotifyRouteImport.update({
    id: '/api/qieman/long-win-plan-notify',
    path: '/api/qieman/long-win-plan-notify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQiemanLongWinPlanRoute = ApiQiemanLongWinPlanRouteImport.update({
  id: '/api/qieman/long-win-plan',
  path: '/api/qieman/long-win-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQiemanLongWinHoldingsDiffNotifyRoute =
  ApiQiemanLongWinHoldingsDiffNotifyRouteImport.update({
    id: '/api/qieman/long-win-holdings-diff-notify',
    path: '/api/qieman/long-win-holdings-diff-notify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQiemanLongWinHoldingsDiffRoute =
  ApiQiemanLongWinHoldingsDiffRouteImport.update({
    id: '/api/qieman/long-win-holdings-diff',
    path: '/api/qieman/long-win-holdings-diff',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFilesWriteRoute = ApiFilesWriteRouteImport.update({
  id: '/api/files/write',
  path: '/api/files/write',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesStatRoute = ApiFilesStatRouteImport.update({
  id: '/api/files/stat',
  path: '/api/files/stat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesReadRoute = ApiFilesReadRouteImport.update({
  id: '/api/files/read',
  path: '/api/files/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesMoveRoute = ApiFilesMoveRouteImport.update({
  id: '/api/files/move',
  path: '/api/files/move',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesMkdirRoute = ApiFilesMkdirRouteImport.update({
  id: '/api/files/mkdir',
  path: '/api/files/mkdir',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesListRoute = ApiFilesListRouteImport.update({
  id: '/api/files/list',
  path: '/api/files/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesDeleteRoute = ApiFilesDeleteRouteImport.update({
  id: '/api/files/delete',
  path: '/api/files/delete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/components-demo': typeof ComponentsDemoRoute
  '/login': typeof LoginRoute
  '/supabase': typeof SupabaseRoute
  '/api/ai-models': typeof ApiAiModelsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-object-url': typeof ApiChatObjectUrlRoute
  '/api/chat-ocr': typeof ApiChatOcrRoute
  '/api/chat-upload-policy': typeof ApiChatUploadPolicyRoute
  '/api/exchange-rate': typeof ApiExchangeRateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/notify': typeof ApiNotifyRoute
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/tg-search': typeof ApiTgSearchRoute
  '/qieman/long-win-plan': typeof QiemanLongWinPlanRoute
  '/api/files/delete': typeof ApiFilesDeleteRoute
  '/api/files/list': typeof ApiFilesListRoute
  '/api/files/mkdir': typeof ApiFilesMkdirRoute
  '/api/files/move': typeof ApiFilesMoveRoute
  '/api/files/read': typeof ApiFilesReadRoute
  '/api/files/stat': typeof ApiFilesStatRoute
  '/api/files/write': typeof ApiFilesWriteRoute
  '/api/qieman/long-win-holdings-diff': typeof ApiQiemanLongWinHoldingsDiffRoute
  '/api/qieman/long-win-holdings-diff-notify': typeof ApiQiemanLongWinHoldingsDiffNotifyRoute
  '/api/qieman/long-win-plan': typeof ApiQiemanLongWinPlanRoute
  '/api/qieman/long-win-plan-notify': typeof ApiQiemanLongWinPlanNotifyRoute
  '/api/skills/$skillId': typeof ApiSkillsSkillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/components-demo': typeof ComponentsDemoRoute
  '/login': typeof LoginRoute
  '/supabase': typeof SupabaseRoute
  '/api/ai-models': typeof ApiAiModelsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-object-url': typeof ApiChatObjectUrlRoute
  '/api/chat-ocr': typeof ApiChatOcrRoute
  '/api/chat-upload-policy': typeof ApiChatUploadPolicyRoute
  '/api/exchange-rate': typeof ApiExchangeRateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/notify': typeof ApiNotifyRoute
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/tg-search': typeof ApiTgSearchRoute
  '/qieman/long-win-plan': typeof QiemanLongWinPlanRoute
  '/api/files/delete': typeof ApiFilesDeleteRoute
  '/api/files/list': typeof ApiFilesListRoute
  '/api/files/mkdir': typeof ApiFilesMkdirRoute
  '/api/files/move': typeof ApiFilesMoveRoute
  '/api/files/read': typeof ApiFilesReadRoute
  '/api/files/stat': typeof ApiFilesStatRoute
  '/api/files/write': typeof ApiFilesWriteRoute
  '/api/qieman/long-win-holdings-diff': typeof ApiQiemanLongWinHoldingsDiffRoute
  '/api/qieman/long-win-holdings-diff-notify': typeof ApiQiemanLongWinHoldingsDiffNotifyRoute
  '/api/qieman/long-win-plan': typeof ApiQiemanLongWinPlanRoute
  '/api/qieman/long-win-plan-notify': typeof ApiQiemanLongWinPlanNotifyRoute
  '/api/skills/$skillId': typeof ApiSkillsSkillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/components-demo': typeof ComponentsDemoRoute
  '/login': typeof LoginRoute
  '/supabase': typeof SupabaseRoute
  '/api/ai-models': typeof ApiAiModelsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-object-url': typeof ApiChatObjectUrlRoute
  '/api/chat-ocr': typeof ApiChatOcrRoute
  '/api/chat-upload-policy': typeof ApiChatUploadPolicyRoute
  '/api/exchange-rate': typeof ApiExchangeRateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/notify': typeof ApiNotifyRoute
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/tg-search': typeof ApiTgSearchRoute
  '/qieman/long-win-plan': typeof QiemanLongWinPlanRoute
  '/api/files/delete': typeof ApiFilesDeleteRoute
  '/api/files/list': typeof ApiFilesListRoute
  '/api/files/mkdir': typeof ApiFilesMkdirRoute
  '/api/files/move': typeof ApiFilesMoveRoute
  '/api/files/read': typeof ApiFilesReadRoute
  '/api/files/stat': typeof ApiFilesStatRoute
  '/api/files/write': typeof ApiFilesWriteRoute
  '/api/qieman/long-win-holdings-diff': typeof ApiQiemanLongWinHoldingsDiffRoute
  '/api/qieman/long-win-holdings-diff-notify': typeof ApiQiemanLongWinHoldingsDiffNotifyRoute
  '/api/qieman/long-win-plan': typeof ApiQiemanLongWinPlanRoute
  '/api/qieman/long-win-plan-notify': typeof ApiQiemanLongWinPlanNotifyRoute
  '/api/skills/$skillId': typeof ApiSkillsSkillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/components-demo'
    | '/login'
    | '/supabase'
    | '/api/ai-models'
    | '/api/chat'
    | '/api/chat-object-url'
    | '/api/chat-ocr'
    | '/api/chat-upload-policy'
    | '/api/exchange-rate'
    | '/api/health'
    | '/api/notify'
    | '/api/skills'
    | '/api/tg-search'
    | '/qieman/long-win-plan'
    | '/api/files/delete'
    | '/api/files/list'
    | '/api/files/mkdir'
    | '/api/files/move'
    | '/api/files/read'
    | '/api/files/stat'
    | '/api/files/write'
    | '/api/qieman/long-win-holdings-diff'
    | '/api/qieman/long-win-holdings-diff-notify'
    | '/api/qieman/long-win-plan'
    | '/api/qieman/long-win-plan-notify'
    | '/api/skills/$skillId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/components-demo'
    | '/login'
    | '/supabase'
    | '/api/ai-models'
    | '/api/chat'
    | '/api/chat-object-url'
    | '/api/chat-ocr'
    | '/api/chat-upload-policy'
    | '/api/exchange-rate'
    | '/api/health'
    | '/api/notify'
    | '/api/skills'
    | '/api/tg-search'
    | '/qieman/long-win-plan'
    | '/api/files/delete'
    | '/api/files/list'
    | '/api/files/mkdir'
    | '/api/files/move'
    | '/api/files/read'
    | '/api/files/stat'
    | '/api/files/write'
    | '/api/qieman/long-win-holdings-diff'
    | '/api/qieman/long-win-holdings-diff-notify'
    | '/api/qieman/long-win-plan'
    | '/api/qieman/long-win-plan-notify'
    | '/api/skills/$skillId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/components-demo'
    | '/login'
    | '/supabase'
    | '/api/ai-models'
    | '/api/chat'
    | '/api/chat-object-url'
    | '/api/chat-ocr'
    | '/api/chat-upload-policy'
    | '/api/exchange-rate'
    | '/api/health'
    | '/api/notify'
    | '/api/skills'
    | '/api/tg-search'
    | '/qieman/long-win-plan'
    | '/api/files/delete'
    | '/api/files/list'
    | '/api/files/mkdir'
    | '/api/files/move'
    | '/api/files/read'
    | '/api/files/stat'
    | '/api/files/write'
    | '/api/qieman/long-win-holdings-diff'
    | '/api/qieman/long-win-holdings-diff-notify'
    | '/api/qieman/long-win-plan'
    | '/api/qieman/long-win-plan-notify'
    | '/api/skills/$skillId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ComponentsDemoRoute: typeof ComponentsDemoRoute
  LoginRoute: typeof LoginRoute
  SupabaseRoute: typeof SupabaseRoute
  ApiAiModelsRoute: typeof ApiAiModelsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiChatObjectUrlRoute: typeof ApiChatObjectUrlRoute
  ApiChatOcrRoute: typeof ApiChatOcrRoute
  ApiChatUploadPolicyRoute: typeof ApiChatUploadPolicyRoute
  ApiExchangeRateRoute: typeof ApiExchangeRateRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiNotifyRoute: typeof ApiNotifyRoute
  ApiSkillsRoute: typeof ApiSkillsRouteWithChildren
  ApiTgSearchRoute: typeof ApiTgSearchRoute
  QiemanLongWinPlanRoute: typeof QiemanLongWinPlanRoute
  ApiFilesDeleteRoute: typeof ApiFilesDeleteRoute
  ApiFilesListRoute: typeof ApiFilesListRoute
  ApiFilesMkdirRoute: typeof ApiFilesMkdirRoute
  ApiFilesMoveRoute: typeof ApiFilesMoveRoute
  ApiFilesReadRoute: typeof ApiFilesReadRoute
  ApiFilesStatRoute: typeof ApiFilesStatRoute
  ApiFilesWriteRoute: typeof ApiFilesWriteRoute
  ApiQiemanLongWinHoldingsDiffRoute: typeof ApiQiemanLongWinHoldingsDiffRoute
  ApiQiemanLongWinHoldingsDiffNotifyRoute: typeof ApiQiemanLongWinHoldingsDiffNotifyRoute
  ApiQiemanLongWinPlanRoute: typeof ApiQiemanLongWinPlanRoute
  ApiQiemanLongWinPlanNotifyRoute: typeof ApiQiemanLongWinPlanNotifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supabase': {
      id: '/supabase'
      path: '/supabase'
      fullPath: '/supabase'
      preLoaderRoute: typeof SupabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components-demo': {
      id: '/components-demo'
      path: '/components-demo'
      fullPath: '/components-demo'
      preLoaderRoute: typeof ComponentsDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qieman/long-win-plan': {
      id: '/qieman/long-win-plan'
      path: '/qieman/long-win-plan'
      fullPath: '/qieman/long-win-plan'
      preLoaderRoute: typeof QiemanLongWinPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tg-search': {
      id: '/api/tg-search'
      path: '/api/tg-search'
      fullPath: '/api/tg-search'
      preLoaderRoute: typeof ApiTgSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills': {
      id: '/api/skills'
      path: '/api/skills'
      fullPath: '/api/skills'
      preLoaderRoute: typeof ApiSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify': {
      id: '/api/notify'
      path: '/api/notify'
      fullPath: '/api/notify'
      preLoaderRoute: typeof ApiNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exchange-rate': {
      id: '/api/exchange-rate'
      path: '/api/exchange-rate'
      fullPath: '/api/exchange-rate'
      preLoaderRoute: typeof ApiExchangeRateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-upload-policy': {
      id: '/api/chat-upload-policy'
      path: '/api/chat-upload-policy'
      fullPath: '/api/chat-upload-policy'
      preLoaderRoute: typeof ApiChatUploadPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-ocr': {
      id: '/api/chat-ocr'
      path: '/api/chat-ocr'
      fullPath: '/api/chat-ocr'
      preLoaderRoute: typeof ApiChatOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-object-url': {
      id: '/api/chat-object-url'
      path: '/api/chat-object-url'
      fullPath: '/api/chat-object-url'
      preLoaderRoute: typeof ApiChatObjectUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-models': {
      id: '/api/ai-models'
      path: '/api/ai-models'
      fullPath: '/api/ai-models'
      preLoaderRoute: typeof ApiAiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills/$skillId': {
      id: '/api/skills/$skillId'
      path: '/$skillId'
      fullPath: '/api/skills/$skillId'
      preLoaderRoute: typeof ApiSkillsSkillIdRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/qieman/long-win-plan-notify': {
      id: '/api/qieman/long-win-plan-notify'
      path: '/api/qieman/long-win-plan-notify'
      fullPath: '/api/qieman/long-win-plan-notify'
      preLoaderRoute: typeof ApiQiemanLongWinPlanNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qieman/long-win-plan': {
      id: '/api/qieman/long-win-plan'
      path: '/api/qieman/long-win-plan'
      fullPath: '/api/qieman/long-win-plan'
      preLoaderRoute: typeof ApiQiemanLongWinPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qieman/long-win-holdings-diff-notify': {
      id: '/api/qieman/long-win-holdings-diff-notify'
      path: '/api/qieman/long-win-holdings-diff-notify'
      fullPath: '/api/qieman/long-win-holdings-diff-notify'
      preLoaderRoute: typeof ApiQiemanLongWinHoldingsDiffNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qieman/long-win-holdings-diff': {
      id: '/api/qieman/long-win-holdings-diff'
      path: '/api/qieman/long-win-holdings-diff'
      fullPath: '/api/qieman/long-win-holdings-diff'
      preLoaderRoute: typeof ApiQiemanLongWinHoldingsDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/write': {
      id: '/api/files/write'
      path: '/api/files/write'
      fullPath: '/api/files/write'
      preLoaderRoute: typeof ApiFilesWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/stat': {
      id: '/api/files/stat'
      path: '/api/files/stat'
      fullPath: '/api/files/stat'
      preLoaderRoute: typeof ApiFilesStatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/read': {
      id: '/api/files/read'
      path: '/api/files/read'
      fullPath: '/api/files/read'
      preLoaderRoute: typeof ApiFilesReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/move': {
      id: '/api/files/move'
      path: '/api/files/move'
      fullPath: '/api/files/move'
      preLoaderRoute: typeof ApiFilesMoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/mkdir': {
      id: '/api/files/mkdir'
      path: '/api/files/mkdir'
      fullPath: '/api/files/mkdir'
      preLoaderRoute: typeof ApiFilesMkdirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/list': {
      id: '/api/files/list'
      path: '/api/files/list'
      fullPath: '/api/files/list'
      preLoaderRoute: typeof ApiFilesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/delete': {
      id: '/api/files/delete'
      path: '/api/files/delete'
      fullPath: '/api/files/delete'
      preLoaderRoute: typeof ApiFilesDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiSkillsRouteChildren {
  ApiSkillsSkillIdRoute: typeof ApiSkillsSkillIdRoute
}

const ApiSkillsRouteChildren: ApiSkillsRouteChildren = {
  ApiSkillsSkillIdRoute: ApiSkillsSkillIdRoute,
}

const ApiSkillsRouteWithChildren = ApiSkillsRoute._addFileChildren(
  ApiSkillsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ComponentsDemoRoute: ComponentsDemoRoute,
  LoginRoute: LoginRoute,
  SupabaseRoute: SupabaseRoute,
  ApiAiModelsRoute: ApiAiModelsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiChatObjectUrlRoute: ApiChatObjectUrlRoute,
  ApiChatOcrRoute: ApiChatOcrRoute,
  ApiChatUploadPolicyRoute: ApiChatUploadPolicyRoute,
  ApiExchangeRateRoute: ApiExchangeRateRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiNotifyRoute: ApiNotifyRoute,
  ApiSkillsRoute: ApiSkillsRouteWithChildren,
  ApiTgSearchRoute: ApiTgSearchRoute,
  QiemanLongWinPlanRoute: QiemanLongWinPlanRoute,
  ApiFilesDeleteRoute: ApiFilesDeleteRoute,
  ApiFilesListRoute: ApiFilesListRoute,
  ApiFilesMkdirRoute: ApiFilesMkdirRoute,
  ApiFilesMoveRoute: ApiFilesMoveRoute,
  ApiFilesReadRoute: ApiFilesReadRoute,
  ApiFilesStatRoute: ApiFilesStatRoute,
  ApiFilesWriteRoute: ApiFilesWriteRoute,
  ApiQiemanLongWinHoldingsDiffRoute: ApiQiemanLongWinHoldingsDiffRoute,
  ApiQiemanLongWinHoldingsDiffNotifyRoute:
    ApiQiemanLongWinHoldingsDiffNotifyRoute,
  ApiQiemanLongWinPlanRoute: ApiQiemanLongWinPlanRoute,
  ApiQiemanLongWinPlanNotifyRoute: ApiQiemanLongWinPlanNotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
