/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupabaseRouteImport } from './routes/supabase'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ComponentsDemoRouteImport } from './routes/components-demo'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QiemanLongWinPlanRouteImport } from './routes/qieman/long-win-plan'
import { Route as ApiTgSearchRouteImport } from './routes/api/tg-search'
import { Route as ApiNotifyRouteImport } from './routes/api/notify'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiExchangeRateRouteImport } from './routes/api/exchange-rate'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiQiemanLongWinPlanNotifyRouteImport } from './routes/api/qieman/long-win-plan-notify'
import { Route as ApiQiemanLongWinPlanRouteImport } from './routes/api/qieman/long-win-plan'
import { Route as ApiQiemanLongWinAssetsRouteImport } from './routes/api/qieman/long-win-assets'
import { Route as ApiQiemanLongWinRouteImport } from './routes/api/qieman/long-win'

const SupabaseRoute = SupabaseRouteImport.update({
  id: '/supabase',
  path: '/supabase',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDemoRoute = ComponentsDemoRouteImport.update({
  id: '/components-demo',
  path: '/components-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QiemanLongWinPlanRoute = QiemanLongWinPlanRouteImport.update({
  id: '/qieman/long-win-plan',
  path: '/qieman/long-win-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTgSearchRoute = ApiTgSearchRouteImport.update({
  id: '/api/tg-search',
  path: '/api/tg-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyRoute = ApiNotifyRouteImport.update({
  id: '/api/notify',
  path: '/api/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExchangeRateRoute = ApiExchangeRateRouteImport.update({
  id: '/api/exchange-rate',
  path: '/api/exchange-rate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQiemanLongWinPlanNotifyRoute =
  ApiQiemanLongWinPlanNotifyRouteImport.update({
    id: '/api/qieman/long-win-plan-notify',
    path: '/api/qieman/long-win-plan-notify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQiemanLongWinPlanRoute = ApiQiemanLongWinPlanRouteImport.update({
  id: '/api/qieman/long-win-plan',
  path: '/api/qieman/long-win-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQiemanLongWinAssetsRoute = ApiQiemanLongWinAssetsRouteImport.update({
  id: '/api/qieman/long-win-assets',
  path: '/api/qieman/long-win-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQiemanLongWinRoute = ApiQiemanLongWinRouteImport.update({
  id: '/api/qieman/long-win',
  path: '/api/qieman/long-win',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/components-demo': typeof ComponentsDemoRoute
  '/login': typeof LoginRoute
  '/supabase': typeof SupabaseRoute
  '/api/chat': typeof ApiChatRoute
  '/api/exchange-rate': typeof ApiExchangeRateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/notify': typeof ApiNotifyRoute
  '/api/tg-search': typeof ApiTgSearchRoute
  '/qieman/long-win-plan': typeof QiemanLongWinPlanRoute
  '/api/qieman/long-win': typeof ApiQiemanLongWinRoute
  '/api/qieman/long-win-assets': typeof ApiQiemanLongWinAssetsRoute
  '/api/qieman/long-win-plan': typeof ApiQiemanLongWinPlanRoute
  '/api/qieman/long-win-plan-notify': typeof ApiQiemanLongWinPlanNotifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/components-demo': typeof ComponentsDemoRoute
  '/login': typeof LoginRoute
  '/supabase': typeof SupabaseRoute
  '/api/chat': typeof ApiChatRoute
  '/api/exchange-rate': typeof ApiExchangeRateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/notify': typeof ApiNotifyRoute
  '/api/tg-search': typeof ApiTgSearchRoute
  '/qieman/long-win-plan': typeof QiemanLongWinPlanRoute
  '/api/qieman/long-win': typeof ApiQiemanLongWinRoute
  '/api/qieman/long-win-assets': typeof ApiQiemanLongWinAssetsRoute
  '/api/qieman/long-win-plan': typeof ApiQiemanLongWinPlanRoute
  '/api/qieman/long-win-plan-notify': typeof ApiQiemanLongWinPlanNotifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/components-demo': typeof ComponentsDemoRoute
  '/login': typeof LoginRoute
  '/supabase': typeof SupabaseRoute
  '/api/chat': typeof ApiChatRoute
  '/api/exchange-rate': typeof ApiExchangeRateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/notify': typeof ApiNotifyRoute
  '/api/tg-search': typeof ApiTgSearchRoute
  '/qieman/long-win-plan': typeof QiemanLongWinPlanRoute
  '/api/qieman/long-win': typeof ApiQiemanLongWinRoute
  '/api/qieman/long-win-assets': typeof ApiQiemanLongWinAssetsRoute
  '/api/qieman/long-win-plan': typeof ApiQiemanLongWinPlanRoute
  '/api/qieman/long-win-plan-notify': typeof ApiQiemanLongWinPlanNotifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/components-demo'
    | '/login'
    | '/supabase'
    | '/api/chat'
    | '/api/exchange-rate'
    | '/api/health'
    | '/api/notify'
    | '/api/tg-search'
    | '/qieman/long-win-plan'
    | '/api/qieman/long-win'
    | '/api/qieman/long-win-assets'
    | '/api/qieman/long-win-plan'
    | '/api/qieman/long-win-plan-notify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/components-demo'
    | '/login'
    | '/supabase'
    | '/api/chat'
    | '/api/exchange-rate'
    | '/api/health'
    | '/api/notify'
    | '/api/tg-search'
    | '/qieman/long-win-plan'
    | '/api/qieman/long-win'
    | '/api/qieman/long-win-assets'
    | '/api/qieman/long-win-plan'
    | '/api/qieman/long-win-plan-notify'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/components-demo'
    | '/login'
    | '/supabase'
    | '/api/chat'
    | '/api/exchange-rate'
    | '/api/health'
    | '/api/notify'
    | '/api/tg-search'
    | '/qieman/long-win-plan'
    | '/api/qieman/long-win'
    | '/api/qieman/long-win-assets'
    | '/api/qieman/long-win-plan'
    | '/api/qieman/long-win-plan-notify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ComponentsDemoRoute: typeof ComponentsDemoRoute
  LoginRoute: typeof LoginRoute
  SupabaseRoute: typeof SupabaseRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiExchangeRateRoute: typeof ApiExchangeRateRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiNotifyRoute: typeof ApiNotifyRoute
  ApiTgSearchRoute: typeof ApiTgSearchRoute
  QiemanLongWinPlanRoute: typeof QiemanLongWinPlanRoute
  ApiQiemanLongWinRoute: typeof ApiQiemanLongWinRoute
  ApiQiemanLongWinAssetsRoute: typeof ApiQiemanLongWinAssetsRoute
  ApiQiemanLongWinPlanRoute: typeof ApiQiemanLongWinPlanRoute
  ApiQiemanLongWinPlanNotifyRoute: typeof ApiQiemanLongWinPlanNotifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supabase': {
      id: '/supabase'
      path: '/supabase'
      fullPath: '/supabase'
      preLoaderRoute: typeof SupabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components-demo': {
      id: '/components-demo'
      path: '/components-demo'
      fullPath: '/components-demo'
      preLoaderRoute: typeof ComponentsDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qieman/long-win-plan': {
      id: '/qieman/long-win-plan'
      path: '/qieman/long-win-plan'
      fullPath: '/qieman/long-win-plan'
      preLoaderRoute: typeof QiemanLongWinPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tg-search': {
      id: '/api/tg-search'
      path: '/api/tg-search'
      fullPath: '/api/tg-search'
      preLoaderRoute: typeof ApiTgSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify': {
      id: '/api/notify'
      path: '/api/notify'
      fullPath: '/api/notify'
      preLoaderRoute: typeof ApiNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exchange-rate': {
      id: '/api/exchange-rate'
      path: '/api/exchange-rate'
      fullPath: '/api/exchange-rate'
      preLoaderRoute: typeof ApiExchangeRateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qieman/long-win-plan-notify': {
      id: '/api/qieman/long-win-plan-notify'
      path: '/api/qieman/long-win-plan-notify'
      fullPath: '/api/qieman/long-win-plan-notify'
      preLoaderRoute: typeof ApiQiemanLongWinPlanNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qieman/long-win-plan': {
      id: '/api/qieman/long-win-plan'
      path: '/api/qieman/long-win-plan'
      fullPath: '/api/qieman/long-win-plan'
      preLoaderRoute: typeof ApiQiemanLongWinPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qieman/long-win-assets': {
      id: '/api/qieman/long-win-assets'
      path: '/api/qieman/long-win-assets'
      fullPath: '/api/qieman/long-win-assets'
      preLoaderRoute: typeof ApiQiemanLongWinAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qieman/long-win': {
      id: '/api/qieman/long-win'
      path: '/api/qieman/long-win'
      fullPath: '/api/qieman/long-win'
      preLoaderRoute: typeof ApiQiemanLongWinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ComponentsDemoRoute: ComponentsDemoRoute,
  LoginRoute: LoginRoute,
  SupabaseRoute: SupabaseRoute,
  ApiChatRoute: ApiChatRoute,
  ApiExchangeRateRoute: ApiExchangeRateRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiNotifyRoute: ApiNotifyRoute,
  ApiTgSearchRoute: ApiTgSearchRoute,
  QiemanLongWinPlanRoute: QiemanLongWinPlanRoute,
  ApiQiemanLongWinRoute: ApiQiemanLongWinRoute,
  ApiQiemanLongWinAssetsRoute: ApiQiemanLongWinAssetsRoute,
  ApiQiemanLongWinPlanRoute: ApiQiemanLongWinPlanRoute,
  ApiQiemanLongWinPlanNotifyRoute: ApiQiemanLongWinPlanNotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
