/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupabaseRouteImport } from './routes/supabase'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ComponentsDemoRouteImport } from './routes/components-demo'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTgSearchRouteImport } from './routes/api/tg-search'
import { Route as ApiNotifyRouteImport } from './routes/api/notify'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SupabaseRoute = SupabaseRouteImport.update({
  id: '/supabase',
  path: '/supabase',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDemoRoute = ComponentsDemoRouteImport.update({
  id: '/components-demo',
  path: '/components-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTgSearchRoute = ApiTgSearchRouteImport.update({
  id: '/api/tg-search',
  path: '/api/tg-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyRoute = ApiNotifyRouteImport.update({
  id: '/api/notify',
  path: '/api/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/components-demo': typeof ComponentsDemoRoute
  '/login': typeof LoginRoute
  '/supabase': typeof SupabaseRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/notify': typeof ApiNotifyRoute
  '/api/tg-search': typeof ApiTgSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/components-demo': typeof ComponentsDemoRoute
  '/login': typeof LoginRoute
  '/supabase': typeof SupabaseRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/notify': typeof ApiNotifyRoute
  '/api/tg-search': typeof ApiTgSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/components-demo': typeof ComponentsDemoRoute
  '/login': typeof LoginRoute
  '/supabase': typeof SupabaseRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/notify': typeof ApiNotifyRoute
  '/api/tg-search': typeof ApiTgSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/components-demo'
    | '/login'
    | '/supabase'
    | '/api/chat'
    | '/api/health'
    | '/api/notify'
    | '/api/tg-search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/components-demo'
    | '/login'
    | '/supabase'
    | '/api/chat'
    | '/api/health'
    | '/api/notify'
    | '/api/tg-search'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/components-demo'
    | '/login'
    | '/supabase'
    | '/api/chat'
    | '/api/health'
    | '/api/notify'
    | '/api/tg-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ComponentsDemoRoute: typeof ComponentsDemoRoute
  LoginRoute: typeof LoginRoute
  SupabaseRoute: typeof SupabaseRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiNotifyRoute: typeof ApiNotifyRoute
  ApiTgSearchRoute: typeof ApiTgSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supabase': {
      id: '/supabase'
      path: '/supabase'
      fullPath: '/supabase'
      preLoaderRoute: typeof SupabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components-demo': {
      id: '/components-demo'
      path: '/components-demo'
      fullPath: '/components-demo'
      preLoaderRoute: typeof ComponentsDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tg-search': {
      id: '/api/tg-search'
      path: '/api/tg-search'
      fullPath: '/api/tg-search'
      preLoaderRoute: typeof ApiTgSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify': {
      id: '/api/notify'
      path: '/api/notify'
      fullPath: '/api/notify'
      preLoaderRoute: typeof ApiNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ComponentsDemoRoute: ComponentsDemoRoute,
  LoginRoute: LoginRoute,
  SupabaseRoute: SupabaseRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiNotifyRoute: ApiNotifyRoute,
  ApiTgSearchRoute: ApiTgSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
